adjective1 = input("Input Adjective: ")
noun1 = input("Input Noun: ")
verb_pasttense1 = input("Input Verb (past tense): ")
adverb1 = input("Input An Adverb: ")
adjective2 = input("Input Adjective: ")
noun2 = input("Input Noun: ")
noun3 = input("Input Noun: ")
adjective3 = input("Input Adjective: ")
verb1 = input("Input Verb: ")
adverb2 = input("Input Adverb: ")
verb_pasttense2 = input("Input Verb (past tense): ")
adjective4 = input("Input Adjective: ")
print("Today i went to the zoo. I saw a " + adjective1)
print(noun1 + " jumping up and down in its tree. ")
print("He " + verb_pasttense1 + " a " + adverb1 + ". ")
print("Through the large tunnel that led to its " + adjective2 + " " + noun2 + ". ")
print("I got some peanuts and passed them through the cage to a gigantic gray")
print(noun3 + " towering above my head. ")
print("Feeding that animal made me hungry. ")
print("I went to get a " + adjective3)
print("scoop of ice cream. It filled my stomach.")
print("Afterwards I had to " + verb1 + " " + adverb2 + " To catch our bus. ")
print("When I got home I " + verb_pasttense2)
print("My mom for a " + adjective4 + " day at the zoo")